
apiVersion: v1
kind: Namespace
metadata:
  name: techday-classic

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: techday-classic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: MyTestApp
  template:
    metadata:
      labels:
        app: MyTestApp
    spec:
      containers:
      - name: nginx-container
        image: nginx:1.14.2
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: techday-classic
spec:
  type: NodePort
  selector:
    app: MyTestApp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30202